{% set data = load_setup_py_data() %}

package:
  name: mpi4py_fft_test
  version: {{ data.get('version') }}

source:
  git_url: ../

build:
  number: 2002

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - cython
    - numpy
    - pip
    - fftw
    - setuptools

  run:
    - python
    - mpi4py
    - mpich
    - {{ pin_compatible('numpy') }}
    - fftw
    - hdf5 * mpi_*
    - h5py * mpi_*
    - netcdf4 * mpi_*

test:
  requires:
    - coverage
    - codecov
    - scipy >=1.0.0
    #- pyfftw

  source_files:
    - tests

  imports:
    - mpi4py_fft
